version: "3"

services:
    web:
        build: .
        ports:
            - "4000:4020"
        depends_on:
            - db
    # build: Ejecuta el docker file para crear la imagen y despues crea el container
    # ports: Sinonimo del docker run -p 4000:4020 api-mongo, hace un puenta entre el puerto 4000 de mi pc con 4020 del container 
    db:
        image: mongo
        restart: always
        expose:
            - "27017"